### ISSUE TITLE
Error, while uploading file to folder in drive

### ISSUE THREAD

**Issue by shivgana** [matAlmeida/pygdrive3#1]
https://github.com/shivgana/python_to_drive_upload

ive uploaded the code used from pygdrive3 site, 
image shown the checking folder and error while uploading file to folder already created in drive

**Comment by matAlmeida** [comment]
So you basically usign the upload method wrong. As you can see in the [Usage](https://github.com/matAlmeida/pygdrive3#usage) section and [code](https://github.com/matAlmeida/pygdrive3/blob/master/pygdrive3/service.py#L57), the upload method receives the folder id, not the folder name.

So you would need to do something like:

```py
folder = drive_service.create_folder('tryupload')
file = drive_service.upload_file('Pydrive', './main.py', folder)
link = drive_service.anyone_permission(file)
```
or
```py
folders = drive_service.list_folders_by_name('tryupload')
file = drive_service.upload_file('Pydrive', './main.py', folders[0]) # This i don't know if is in the index 0, you need to find out 
link = drive_service.anyone_permission(file)
```

**Comment by shivgana** [comment]
First solution not a proper solution for my problem, bcuz i done want to create the folder. It is already created in drive.
The Second solution was not worked, but some how i resolved,.
Folders variable is list of dictionary contain id of deleted and existing folders, but latest folder id is last id.
folders = drive_service.list_folders_by_name('tryupload')
file = drive_service.upload_file('Pydrive', './main.py', folders[-1]['id']) # This -1 index value is recently created folder. 
link = drive_service.anyone_permission(file)
