### ISSUE TITLE
how to set mimetype of  the file

### ISSUE THREAD

**Issue by shivgana** [matAlmeida/pygdrive3#2]
after uploading any file to drive, its extension are setting to plain file.
####
folders = drive_service.list_folders_by_name('python_upload')
file = drive_service.upload_file('Pydrive.py', './main.py', folders[-1]['id'])
link = drive_service.anyone_permission(file)
####

**Comment by matAlmeida** [comment]
So, the package was only intended to `guess` the mime type from the file extension. I made a update version that adds that feature, please update to [v0.7.0](https://pypi.org/project/pygdrive3/)

**Comment by shivgana** [comment]
ive updated to v0.7.0 now tho specify mimetype while uploading

**Comment by matAlmeida** [comment]
> ive updated to v0.7.0 now tho specify mimetype while uploading

You can pass as the last argument, like:

```py
file = drive_service.upload_file('Pydrive.py', './main.py', folders[-1]['id'], 'image/png')
```
